$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: diabetes-pipeline
settings:
  default_compute: azureml:cpu-cluster

inputs:
  training_data:
    type: uri_folder
    path: azureml:diabetes-dev-data:1
  reg_rate: 0.01

jobs:
  train_for_diabetes:
    code: model
    command: >-
      python train.py --training_data ${{inputs.training_data}}


    inputs:
      training_data: ${{parent.inputs.training_data}}
      reg_rate: ${{parent.inputs.reg_rate}}

    environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
    compute: ci-instance
    description: an experiment
