name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  # train_development:
  #   runs-on: ubuntu-latest
  #   environment: development
  #   steps:
  #     - name: Check out repo
  #       uses: actions/checkout@main
  #     - name: Install az ml extension
  #       run: az extension add -n ml -y
  #     - name: Azure login
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{secrets.AZURE_CREDENTIALS}}
  #     - name: Azure CLI Action
  #       uses: Azure/cli@v1
  #       with:
  #         inlineScript: |
  #           az extension add -n ml -y
  #           az ml compute create -g mikouml -w mikouml -n ci-instance --type ComputeInstance
  #           az ml job create --file src/job_pipeline.yml -g mikouml -n "simulation-for-run-${{ github.run_id }}" -w mikouml --set inputs.training_data.path=file --set inputs.training_data.path='azureml:diabetes-dev-data:1' --stream --set display_name='diabetes-development' --set inputs.run_id='${{ github.run_id }}' --set jobs.train_for_diabetes.compute=edgeTarget --set jobs.train_for_diabetes.name="diabetes-development-model-${{ github.run_id }}"

  train_production:
    # needs: train_development
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az extension add -n ml -y
            az ml compute create -g mikouml -w mikouml -n ci-instance --type ComputeInstance
            az ml job create --file src/job_pipeline.yml -g mikouml -n "simulation-for-production-run-${{ github.run_id }}" -w mikouml --set inputs.training_data.path=folder --set inputs.training_data.path="azureml:diabetes-production-data:1" --set display_name='diabetes-production' --set inputs.run_id=${{ github.run_id }} --stream --set jobs.train_for_diabetes.name="diabetes-production-model-${{ github.run_id }}"
  deploy_production:
    needs: train_production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az extension add -n ml -y
            JOB_NAME=$(az ml job list --query "[0].name" -g mikouml -w mikouml | tr -d '"')
            echo $JOB_NAME

            az ml model create --name "diabetes-mlflow-model" --type "mlflow_model" --path "azureml://jobs/diabetes-production-model-${{ github.run_id }}/outputs/artifacts/model" -g mikouml -w mikouml
            az ml online-deployment create --name diabetes-deployment --endpoint $ENDPOINT_NAME -f endpoints/deployment.yaml --all-traffic -g mikouml -w mikouml
