name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  train_development:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az extension add -n ml -y
            az ml compute create -g mikouml -w mikouml -n ci-instance --type ComputeInstance
            az ml job create --file src/job_pipeline.yml -g mikouml -n "simulation-for-run-${{ github.run_id }}" -w mikouml --set inputs.training_data.path=file --set inputs.training_data.path='azureml:diabetes-dev-data:1' --stream --set display_name='diabetes-development'

  train_production:
    needs: train_development
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az extension add -n ml -y
            az ml compute create -g mikouml -w mikouml -n ci-instance --type ComputeInstance
            az ml job create --file src/job_pipeline.yml -g mikouml -n "simulation-for-production-run-${{ github.run_id }}" -w mikouml --set inputs.training_data.path=folder --set inputs.training_data.path="azureml:diabetes-production-data:1" --set display_name='diabetes-production'
  deploy_production:
    needs: train_production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          inlineScript: |
            JOB_NAME="simulation-for-production-run-${{ github.run_id }}"
            az extension add -n ml -y
            az ml model create --name "diabetes-mlflow-model" --type "mlflow_model" --path "azureml://jobs/$JOB_NAME/outputs/artifacts/model"
            az ml online-deployment create --name diabetes-deployment --endpoint $ENDPOINT_NAME -f endpoints/deployment.yaml --all-traffic
